name: sentinelprep
channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.13
  - numpy >=1.24
  - rasterio >=1.3
  - scikit-learn >=1.4
  - tqdm >=4.66
  - pip
  - pip:
      - sentinelprep @ git+https://github.com/eas510/Sentinelprep.git@main
